"""
SACHITRA Presentation (PPT) Generation Demo
AI-powered slide generation with contextual images
"""

import numpy as np
from typing import List, Dict, Optional, Any
from dataclasses import dataclass, field
from pathlib import Path
import sys

sys.path.append(str(Path(__file__).parent.parent.parent))

from src.core.sachitra_inference import SACHITRAInference, SACHITRAConfig


@dataclass
class Slide:
    """Individual slide with content and optional image"""
    title: str
    content: str
    bullets: List[str] = field(default_factory=list)
    image_prompt: Optional[str] = None
    notes: Optional[str] = None
    layout: str = "title_content"  # title_only, title_content, two_column, image_only

    def generate_image_prompt(self) -> str:
        """Generate appropriate image prompt from slide content"""
        if self.image_prompt:
            return self.image_prompt

        # Generate from title and content
        prompt = f"{self.title}"
        if self.bullets:
            prompt += f" - {self.bullets[0]}"
        return prompt


@dataclass
class PresentationConfig:
    """Configuration for presentation generation"""
    slide_size: tuple = (1920, 1080)  # 16:9
    title_font_size: int = 44
    content_font_size: int = 24
    bullet_font_size: int = 20
    include_images: bool = True
    image_placement: str = "right"  # left, right, background
    color_scheme: str = "professional"  # professional, vibrant, minimal


class PPTGenerator:
    """
    AI-powered presentation generator

    Creates slides with contextual images generated by SACHITRA.
    """

    def __init__(self, model: Optional[SACHITRAInference] = None,
                 config: Optional[PresentationConfig] = None):
        self.model = model or SACHITRAInference()
        self.config = config or PresentationConfig()

        self.slides: List[Slide] = []
        self.generated_images: Dict[int, np.ndarray] = {}

    def add_slide(self, slide: Slide) -> None:
        """Add a slide to the presentation"""
        self.slides.append(slide)

    def create_presentation(self, topic: str, num_slides: int = 5,
                           include_images: bool = True) -> List[Slide]:
        """
        Auto-generate a presentation on a topic

        Args:
            topic: Presentation topic
            num_slides: Number of slides to generate
            include_images: Whether to generate images

        Returns:
            List of generated slides
        """
        self.slides = []

        # Template slide structure
        slide_templates = [
            {'title': f'{topic}: Introduction', 'layout': 'title_content',
             'bullets': ['Overview of the topic', 'Key concepts to understand']},
            {'title': f'Understanding {topic}', 'layout': 'title_content',
             'bullets': ['Fundamental principles', 'Core components']},
            {'title': f'{topic} in Practice', 'layout': 'two_column',
             'bullets': ['Real-world applications', 'Case studies']},
            {'title': f'Benefits of {topic}', 'layout': 'title_content',
             'bullets': ['Key advantages', 'Impact and value']},
            {'title': f'Conclusion: {topic}', 'layout': 'title_content',
             'bullets': ['Summary', 'Next steps']}
        ]

        for i, template in enumerate(slide_templates[:num_slides]):
            slide = Slide(
                title=template['title'],
                content="",
                bullets=template['bullets'],
                layout=template['layout']
            )

            # Generate image prompt
            slide.image_prompt = self._generate_image_prompt(slide.topic, i)

            self.add_slide(slide)

        # Generate images for each slide
        if include_images:
            self.generate_slide_images()

        return self.slides

    def _generate_image_prompt(self, title: str, slide_idx: int) -> str:
        """Generate image prompt based on slide content"""
        prompts = {
            0: f"Professional introduction imagery for: {title}",
            1: f"Educational concept illustration: {title}",
            2: f"Real-world application scene: {title}",
            3: f"Benefits and value visualization: {title}",
            4: f"Conclusion and summary graphic: {title}"
        }
        return prompts.get(slide_idx, f"Illustration for: {title}")

    def generate_slide_images(self, num_steps: int = 25) -> None:
        """Generate images for all slides"""
        for i, slide in enumerate(self.slides):
            print(f"  Generating image for slide {i+1}: {slide.title}")

            image = self.model.generate(
                slide.image_prompt,
                num_steps=num_steps,
                seed=i * 100
            )

            self.generated_images[i] = image

    def render_slide_image(self, slide_idx: int) -> np.ndarray:
        """Render a slide as an image"""
        slide = self.slides[slide_idx]

        if slide_idx in self.generated_images:
            return self.generated_images[slide_idx]

        # Generate if not exists
        image = self.model.generate(
            slide.image_prompt or slide.title,
            num_steps=25,
            seed=slide_idx * 100
        )

        self.generated_images[slide_idx] = image
        return image

    def export_as_html(self, output_path: str) -> str:
        """
        Export presentation as HTML (browser-native)

        Args:
            output_path: Path to save HTML file

        Returns:
            Path to generated HTML
        """
        html_content = self._generate_html_presentation()

        with open(output_path, 'w') as f:
            f.write(html_content)

        return output_path

    def _generate_html_presentation(self) -> str:
        """Generate HTML presentation content"""
        slides_html = []

        for i, slide in enumerate(self.slides):
            img_html = ""
            if i in self.generated_images:
                # Convert image to base64 for embedding
                import base64
                from io import BytesIO
                import matplotlib.pyplot as plt

                fig, ax = plt.subplots(figsize=(16, 9))
                ax.imshow(self.generated_images[i], cmap='gray')
                ax.axis('off')

                buf = BytesIO()
                plt.savefig(buf, format='png', dpi=100, bbox_inches='tight')
                plt.close(fig)
                buf.seek(0)
                img_b64 = base64.b64encode(buf.read()).decode()
                img_html = f'<img src="data:image/png;base64,{img_b64}" class="slide-image">'

            slide_html = f"""
            <div class="slide" id="slide-{i}">
                <div class="slide-content">
                    <h1 class="slide-title">{slide.title}</h1>
                    <div class="slide-body">
                        {img_html}
                        <ul class="slide-bullets">
                            {"".join(f"<li>{b}</li>" for b in slide.bullets)}
                        </ul>
                    </div>
                </div>
                <div class="slide-notes">
                    <p>Notes: {slide.notes or 'Presenter notes go here...'}</p>
                </div>
            </div>
            """
            slides_html.append(slide_html)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SACHITRA Presentation</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #1a1a2e; color: white; }}
        .presentation {{ width: 100%; height: 100vh; overflow: hidden; }}
        .slide {{ display: none; width: 100%; height: 100vh; padding: 60px; background: linear-gradient(135deg, #16213e 0%, #1a1a2e 100%); }}
        .slide.active {{ display: flex; flex-direction: column; }}
        .slide-content {{ flex: 1; display: flex; flex-direction: column; justify-content: center; }}
        .slide-title {{ font-size: 48px; margin-bottom: 40px; color: #00d9ff; text-align: center; }}
        .slide-body {{ display: flex; gap: 40px; align-items: center; }}
        .slide-image {{ max-width: 45%; max-height: 60vh; border-radius: 12px; box-shadow: 0 20px 60px rgba(0,217,255,0.2); }}
        .slide-bullets {{ flex: 1; font-size: 28px; line-height: 1.8; }}
        .slide-bullets li {{ margin-bottom: 16px; color: #e0e0e0; }}
        .slide-notes {{ font-size: 16px; color: #8892b0; margin-top: 20px; text-align: center; }}
        .nav {{ position: fixed; bottom: 30px; left: 50%; transform: translateX(-50%); display: flex; gap: 20px; }}
        .nav button {{ padding: 12px 30px; border: none; border-radius: 8px; background: #00d9ff; color: #1a1a2e; font-size: 18px; cursor: pointer; }}
        .nav button:hover {{ background: #00ff88; }}
        .progress {{ position: fixed; top: 20px; right: 30px; font-size: 18px; color: #8892b0; }}
        .slide-number {{ position: fixed; bottom: 30px; right: 30px; font-size: 16px; color: #8892b0; }}
    </style>
</head>
<body>
    <div class="presentation">
        {''.join(slides_html)}
    </div>

    <div class="nav">
        <button onclick="prevSlide()">Previous</button>
        <button onclick="nextSlide()">Next</button>
    </div>

    <div class="progress">SACHITRA Generated Presentation</div>
    <div class="slide-number" id="slideNum">1 / {len(self.slides)}</div>

    <script>
        let currentSlide = 0;
        const slides = document.querySelectorAll('.slide');
        const totalSlides = slides.length;

        function showSlide(n) {{
            slides.forEach(s => s.classList.remove('active'));
            slides[n].classList.add('active');
            document.getElementById('slideNum').textContent = `${'${n + 1}'} / ${'${totalSlides}'}`;
        }}

        function nextSlide() {{
            currentSlide = (currentSlide + 1) % totalSlides;
            showSlide(currentSlide);
        }}

        function prevSlide() {{
            currentSlide = (currentSlide - 1 + totalSlides) % totalSlides;
            showSlide(currentSlide);
        }}

        document.addEventListener('keydown', (e) => {{
            if (e.key === 'ArrowRight' || e.key === ' ') nextSlide();
            if (e.key === 'ArrowLeft') prevSlide();
        }});

        showSlide(0);
    </script>
</body>
</html>"""

        return html

    def export_as_images(self, output_dir: str) -> List[str]:
        """
        Export presentation as a series of images

        Args:
            output_dir: Directory to save images

        Returns:
            List of saved image paths
        """
        import matplotlib.pyplot as plt

        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        paths = []

        for i, slide in enumerate(self.slides):
            fig, ax = plt.subplots(figsize=(16, 9), dpi=100)
            ax.set_facecolor('#16213e')

            # Title
            ax.text(0.5, 0.85, slide.title, fontsize=36, ha='center',
                   va='top', color='#00d9ff', fontweight='bold',
                   transform=ax.transAxes)

            # Image if available
            if i in self.generated_images:
                ax.imshow(self.generated_images[i], cmap='gray',
                         extent=[0.3, 0.7, 0.3, 0.7], aspect='auto')

            # Bullets
            bullet_text = '\n'.join(f"• {b}" for b in slide.bullets)
            ax.text(0.5, 0.35, bullet_text, fontsize=18, ha='center',
                   va='top', color='#e0e0e0', transform=ax.transAxes,
                   linespacing=1.5)

            ax.axis('off')

            # Save
            path = output_path / f"slide_{i+1:02d}.png"
            plt.savefig(path, bbox_inches='tight', facecolor='#16213e')
            plt.close()

            paths.append(str(path))
            print(f"  Saved: {path}")

        return paths

    def get_statistics(self) -> Dict[str, Any]:
        """Get presentation generation statistics"""
        return {
            'num_slides': len(self.slides),
            'images_generated': len(self.generated_images),
            'slide_layouts': [s.layout for s in self.slides]
        }


def run_ppt_demo():
    """Run presentation generation demo"""
    print("SACHITRA Presentation Generation Demo")
    print("=" * 60)

    # Create generator
    config = PresentationConfig()
    generator = PPTGenerator(config=config)

    # Create presentation
    topic = "AI for Research"
    num_slides = 5

    print(f"\nGenerating presentation on: '{topic}'")
    print(f"Number of slides: {num_slides}")

    slides = generator.create_presentation(topic, num_slides, include_images=True)

    print(f"\nGenerated {len(slides)} slides:")
    for i, slide in enumerate(slides):
        print(f"  Slide {i+1}: {slide.title}")
        print(f"    Layout: {slide.layout}")
        print(f"    Bullets: {len(slide.bullets)}")

    # Export as HTML
    output_dir = Path(__file__).parent
    html_path = generator.export_as_html(str(output_dir / "presentation.html"))
    print(f"\nHTML presentation saved: {html_path}")

    # Export as images
    img_paths = generator.export_as_images(str(output_dir / "slides"))
    print(f"\nSlide images saved to: {output_dir / 'slides'}")

    print("\n" + "=" * 60)
    print("Presentation Statistics:")
    stats = generator.get_statistics()
    for key, value in stats.items():
        print(f"  {key}: {value}")

    print("\nDemo complete!")
    print("Open 'presentation.html' in a browser to view the presentation.")


if __name__ == "__main__":
    run_ppt_demo()